# @package _global_

config:
  model:
    custom_model_config:
      polytope_storage_method: seed #seed, file
      polytope_generation_method: points #points, rejection_sampling, unconstrained
      polytope_generation_data:
        #storage method seed
        seed: 1
        #points method
        n_points: 30
        #rejection_sampling method
        number_of_constraints: 5
        #storage method file
        path: null #path to the file where the polytope is stored
