# logging_config.yaml

version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(message)s'

handlers:
  console_handler:
    class: logging.StreamHandler
    level: INFO
    formatter: simple

  file_handler:
    class: logging.FileHandler
    filename: ../.logging/monitoring.log
    level: DEBUG
    formatter: simple

loggers:
  custom_logger:
    level: DEBUG
    handlers: [console_handler, file_handler]
    propagate: no